### ISSUE TITLE
note: todo

### ISSUE THREAD

**Issue by Apache553** [Apache553/SubtitleFontHelper#8]
- [ ] fix event manifest. 
  - [ ] registration command line. 
  - [ ] unify format -> string only
- [ ] relaxed config validation
- [ ] index precedence. higher masks lower
- [ ] toaster notification
- [ ] user interface improvement. 
  - [ ] error message
  - [ ] configuration wizard
- [ ] quick import fonts from archives
- [ ] http/https hosted font index
- [ ] make a schedule for tasks above🔥
